//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suscripcion
    {
        public int Id { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public Nullable<int> planId { get; set; }
    
        public virtual Planes Planes { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
