//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wod()
        {
            this.WodXEjercicio = new HashSet<WodXEjercicio>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> DiaId { get; set; }
    
        public virtual Dia Dia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WodXEjercicio> WodXEjercicio { get; set; }
    }
}
