//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDDLibreria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoachBusterEntities1 : DbContext
    {
        public CoachBusterEntities1()
            : base("name=CoachBusterEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Dia> Dia { get; set; }
        public virtual DbSet<GrupoEjercicios> GrupoEjercicios { get; set; }
        public virtual DbSet<Planes> Planes { get; set; }
        public virtual DbSet<Progreso> Progreso { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Suscripcion> Suscripcion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Wod> Wod { get; set; }
        public virtual DbSet<WodXEjercicio> WodXEjercicio { get; set; }
    }
}
