//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDDLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progreso
    {
        public int Id { get; set; }
        public int IdSuscripcion { get; set; }
        public int IdWodXEjercicio { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool IsCompleted { get; set; }
    
        public virtual Suscripcion Suscripcion { get; set; }
        public virtual WodXEjercicio WodXEjercicio { get; set; }
    }
}
