//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDDLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class WodXEjercicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WodXEjercicio()
        {
            this.Progreso = new HashSet<Progreso>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdWod { get; set; }
        public Nullable<int> IdGrupoEjercicios { get; set; }
    
        public virtual GrupoEjercicios GrupoEjercicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progreso> Progreso { get; set; }
        public virtual Wod Wod { get; set; }
    }
}
