//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDDLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class WodXEjercicio
    {
        public int Id { get; set; }
        public Nullable<int> IdWod { get; set; }
        public Nullable<int> IdGrupoEjercicios { get; set; }
    
        public virtual GrupoEjercicios GrupoEjercicios { get; set; }
        public virtual Wod Wod { get; set; }
    }
}
